### ISSUE TITLE
Adding portrait class to photo widget

### ISSUE THREAD

**Issue by krackydile** [SparkartGroupInc/jungle-solidus#19]
A featured that is missing from the photo widget is knowing if an image is portrait or not. The original Clique Tools markup would include a `portrait` class on the image tag.

An example of where the class would be needed:
https://github.com/SparkartGroupInc/jungle-solidus/blob/master/widgets/photo/browse_default.hbs#L13

**Comment by pushred** [comment]
James actually [built something for this][1], just needs to be added here. @joanniclaborde 

[1]: https://github.com/SparkartGroupInc/jungle-solidus/blob/master/helpers/portrait.js

**Comment by joanniclaborde** [comment]
Fixed in v1.6.1
