### ISSUE TITLE
Incorrect npm registry name for subscribe-email block

### ISSUE THREAD

**Issue by krackydile** [SparkartGroupInc/jungle-solidus#23]
The wiki states [here](https://github.com/SparkartGroupInc/jungle-solidus/wiki/Widgets) that the registry name for the subscribe widget is `subscribe-email`. That doesn't exist. It is actually `blocks-subscribe-email `.

**Comment by josiahsprague** [comment]
The GitHub repo name is [blocks/subscribe-email](https://github.com/blocks/subscribe-email/), but on the npm registry it's named [blocks-subscribe-email](https://www.npmjs.com/package/blocks-subscribe-email). I updated the wiki to be a little bit clearer (hopefully).

**Comment by joanniclaborde** [comment]
Don't forget to also update the readme! https://github.com/blocks/subscribe-email/
