### ISSUE TITLE
Fingerprinted assets aren't used

### ISSUE THREAD

**Issue by pushred** [SparkartGroupInc/jungle-solidus#32]
Fingerprinted CSS and JS aren't used on sites currently because they are loaded from these partials:

https://github.com/SparkartGroupInc/jungle-solidus/blob/master/defaults/styles.hbs
https://github.com/SparkartGroupInc/jungle-solidus/blob/master/defaults/scripts.hbs

We could point the fingerprinting script at these partials in order to get the primary bundle reference updated, but the per page assets won't work because those are defined at runtime.

To fix this there's perhaps another task that could be run that expands these references in-place, or if gulp-filerev-replace could generate a manifest a helper could be used to expand the current filenames.

**Comment by joanniclaborde** [comment]
I think a manifest is the way to go, I'll add that option to gulp-filerev-replace, and a helper to jungle-solidus, that looks for the manifest file.
